language: java

  addons:
  hosts:
    - mockito-cd
  hostname: mockito-cd

notifications:
  email: false

services:
  - mysql
  
before_script:
- mysql -e 'CREATE DATABASE db;'

script: 
  - cd proyecto-tp-final
  - mvn install -B -V -e
  

